name: Pull Request Checks

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      DEBUG: '*'
      NX_VERBOSE_LOGGING: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (CI mode, skip ESLint)
        run: |
          echo "Running Nx tests..."
          npx nx run-many --target=test --all --coverage --ci --skip-nx-cache --skip-eslint || {
            echo "::error ::Tests failed";
            exit 1;
          }

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
